-- Schema inicial do Wikify.
--
-- Reproduz o que o ddl-auto=update vinha gerando a partir das entidades JPA.
-- A partir daqui o Hibernate roda em modo 'validate': ele confere e nunca altera.
--
-- Nunca edite este arquivo depois que ele tiver sido aplicado — o Flyway guarda
-- o checksum de cada migration e recusa a subir se o conteúdo mudar. Toda
-- alteração de schema vira um arquivo novo (V2__..., V3__...).


-- =============================================================================
-- Usuários e departamentos
-- =============================================================================

CREATE TABLE users (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    login       VARCHAR(255) NOT NULL,
    password    VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    system_role VARCHAR(255) NOT NULL,

    CONSTRAINT uk_users_login UNIQUE (login),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE departments (
    id   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,

    CONSTRAINT uk_departments_slug UNIQUE (slug)
);

-- Vínculo usuário↔departamento. É aqui que mora o papel de verdade: a mesma
-- pessoa pode ser MANAGER de um departamento e READER de outro.
CREATE TABLE department_membership (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL,
    department_id BIGINT       NOT NULL,
    role          VARCHAR(255) NOT NULL,

    CONSTRAINT fk_membership_user       FOREIGN KEY (user_id)       REFERENCES users (id),
    CONSTRAINT fk_membership_department FOREIGN KEY (department_id) REFERENCES departments (id),
    CONSTRAINT uk_membership_user_department UNIQUE (user_id, department_id)
);

-- O Postgres não cria índice automático para chave estrangeira, e a consulta
-- "quais vínculos deste usuário" roda a cada requisição autenticada.
CREATE INDEX idx_membership_user_id       ON department_membership (user_id);
CREATE INDEX idx_membership_department_id ON department_membership (department_id);


-- =============================================================================
-- Documentos e revisões
-- =============================================================================

CREATE TABLE documents (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR(255) NOT NULL,
    slug             VARCHAR(255) NOT NULL,
    path             VARCHAR(255) NOT NULL,
    department_id    BIGINT       NOT NULL,
    parent_id        BIGINT,
    position         INTEGER      NOT NULL,
    status           VARCHAR(255) NOT NULL,
    edit_policy      VARCHAR(255) NOT NULL,
    created_by       BIGINT       NOT NULL,
    content_markdown TEXT         NOT NULL,
    created_at       TIMESTAMP(6),
    updated_at       TIMESTAMP(6),

    CONSTRAINT fk_documents_department FOREIGN KEY (department_id) REFERENCES departments (id),
    CONSTRAINT fk_documents_parent     FOREIGN KEY (parent_id)     REFERENCES documents (id),
    CONSTRAINT fk_documents_created_by FOREIGN KEY (created_by)    REFERENCES users (id),

    -- O path é a URL do documento: precisa ser único no sistema inteiro
    CONSTRAINT uk_documents_path UNIQUE (path)
);

-- Filtro de toda leitura: WHERE department_id IN (...) AND status = 'PUBLISHED'
CREATE INDEX idx_documents_department_status ON documents (department_id, status);
CREATE INDEX idx_documents_parent_id         ON documents (parent_id);

-- Retrato imutável do documento a cada salvamento.
CREATE TABLE revisions (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR(255),
    content_markdown TEXT         NOT NULL,
    document_id      BIGINT       NOT NULL,
    author_id        BIGINT       NOT NULL,
    created_at       TIMESTAMP(6) NOT NULL,

    CONSTRAINT fk_revisions_document FOREIGN KEY (document_id) REFERENCES documents (id),
    CONSTRAINT fk_revisions_author   FOREIGN KEY (author_id)   REFERENCES users (id)
);

-- Listar o histórico de um documento é a consulta principal desta tabela.
CREATE INDEX idx_revisions_document_id ON revisions (document_id);

-- Departamentos convidados: leem o documento sem poder editá-lo.
-- Modelada, mas ainda sem nenhum endpoint que a alimente.
CREATE TABLE document_department_access (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id   BIGINT NOT NULL,
    department_id BIGINT NOT NULL,

    CONSTRAINT fk_access_document   FOREIGN KEY (document_id)   REFERENCES documents (id),
    CONSTRAINT fk_access_department FOREIGN KEY (department_id) REFERENCES departments (id),
    CONSTRAINT uk_access_document_department UNIQUE (document_id, department_id)
);

CREATE INDEX idx_access_department_id ON document_department_access (department_id);
