-- Aprovação pelo gestor (task 6.7).
--
-- Duas coisas entram aqui, e elas são EIXOS SEPARADOS — é o que define o
-- desenho da funcionalidade e o que estas colunas precisam sustentar:
--
--   status      responde "o leitor enxerga?"      DRAFT · PUBLISHED
--   validation  responde "o gestor já conferiu?"  NONE · PENDING · APPROVED · REJECTED
--
-- Um documento no ar e ainda não conferido é estado legítimo, não defeito: é o
-- que acontece quando a chave do departamento está desligada — publica na hora
-- e continua na fila do gestor até alguém conferir. A chave não decide se o
-- gestor confere, decide se a publicação espera por isso.


-- ─── 1. Verificação no documento ────────────────────────────────────────────

-- DEFAULT 'NONE' faz o preenchimento das linhas existentes no mesmo comando, e
-- fica na coluna depois: é o valor certo para qualquer documento que nasça fora
-- do fluxo de verificação.
ALTER TABLE documents ADD COLUMN validation VARCHAR(255) NOT NULL DEFAULT 'NONE';

-- Quem conferiu e quando. Dois campos em vez de um booleano porque é
-- exatamente isso que se quer saber seis meses depois — "aprovado" sozinho não
-- responde nada.
ALTER TABLE documents ADD COLUMN validation_at TIMESTAMP(6);
ALTER TABLE documents ADD COLUMN validation_by BIGINT;

-- VARCHAR(255) e não TEXT de propósito: o campo `rejectionReason` da entidade
-- não tem `@Column`, então o Hibernate o mapeia para varchar(255) e é isso que
-- o `ddl-auto=validate` vai procurar no boot. Para aceitar recusas mais longas,
-- anote `@Column(columnDefinition = "TEXT")` na entidade E troque aqui — os
-- dois lados juntos, ou a aplicação não sobe.
ALTER TABLE documents ADD COLUMN rejection_reason VARCHAR(255);

ALTER TABLE documents
    ADD CONSTRAINT fk_documents_validation_by FOREIGN KEY (validation_by) REFERENCES users (id);

-- A fila do gestor é `department_id + validation`, do mesmo jeito que a leitura
-- é `department_id + status` (idx_documents_department_status, da V1).
CREATE INDEX idx_documents_department_validation ON documents (department_id, validation);


-- ─── 2. A chave, por departamento ───────────────────────────────────────────
--
-- Tabela à parte e não coluna em `departments` porque a configuração carrega
-- quem virou a chave e quando — a pergunta "por que isso foi ao ar sem
-- conferência?" seis meses depois.

CREATE TABLE department_approval_publish (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id     BIGINT       NOT NULL,

    -- DEFAULT FALSE: a wiki é construída pelo departamento, e exigir aprovação
    -- é o gargalo que a decisão original evitou. Ligar a trava tem que ser um
    -- ato deliberado do gestor, nunca o que acontece por omissão.
    approval_required BOOLEAN      NOT NULL DEFAULT FALSE,

    -- Nulo enquanto ninguém mexeu na chave desde a criação do departamento.
    changed_by        BIGINT,
    changed_at        TIMESTAMP(6) NOT NULL,

    CONSTRAINT fk_department_approval_department FOREIGN KEY (department_id) REFERENCES departments (id),
    CONSTRAINT fk_department_approval_changed_by FOREIGN KEY (changed_by)    REFERENCES users (id),

    -- O nome casa com o @UniqueConstraint da entidade. Um departamento tem uma
    -- configuração, nunca duas.
    CONSTRAINT uk_department_approval_config UNIQUE (department_id)
);

-- Uma linha para cada departamento que já existe.
--
-- Isto NÃO é opcional. O `DepartmentService` só cria a configuração para
-- departamentos novos, e o `approvedDocument` faz `.orElseThrow()` quando não
-- acha — sem este INSERT, publicar qualquer documento de qualquer departamento
-- anterior a esta migration estoura com "Configuração não encontrada".
INSERT INTO department_approval_publish (department_id, approval_required, changed_at)
SELECT id, FALSE, now() FROM departments;
